#!/bin/python
import imaplib
import os
from dotenv import load_dotenv

# Load email and password from environment variables
load_dotenv()

obj = imaplib.IMAP4_SSL('imap.gmail.com', 993)
obj.login(os.getenv('EMAIL'), os.getenv('PASSWORD'))
obj.select()

print(len(obj.search(None, 'UnSeen')[1][0].split()))
